#!/usr/bin/env python

import os
import pexpect
import re
import requests
import time

import rospy

import hgbot_infra.leds as leds
from hgbot_infra.srv import HGBCmd

     
def led_server():
    rospy.init_node('led', log_level=rospy.DEBUG)

    rospy.logdebug("Creating LEDs object")
    ledsrv = leds.LEDService(1)
    
    rospy.logdebug("Launch LED service")
    rospy.Service('LED_service', HGBCmd, ledsrv.callback)

    DURATION = 0.5
    d = rospy.Duration(DURATION)  # wake up every 1/2 seconds to report status
    while not rospy.is_shutdown():
        ledsrv.process(DURATION)
        rospy.sleep(d)


if __name__ == "__main__":
    led_server()
